//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class EventInfo
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public EventInfo()
        {
            this.EventImage1 = new HashSet<EventImage>();
            this.EventRefrences = new HashSet<EventRefrences>();
        }
    
        public int eventID { get; set; }
        public string eventNameEn { get; set; }
        public string eventNameAr { get; set; }
        public string eventDescEn { get; set; }
        public string eventDescAr { get; set; }
        public Nullable<double> latitude { get; set; }
        public Nullable<double> longitude { get; set; }
        public Nullable<int> eventTypeID { get; set; }
        public Nullable<int> countryID { get; set; }
        public Nullable<System.DateTime> eventDate { get; set; }
        public Nullable<int> userID { get; set; }
        public Nullable<int> statusID { get; set; }
        public string eventImage { get; set; }
        public Nullable<System.DateTime> dateAdd { get; set; }
    
        public virtual Countries Countries { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<EventImage> EventImage1 { get; set; }
        public virtual EventTypes EventTypes { get; set; }
        public virtual Users Users { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<EventRefrences> EventRefrences { get; set; }
    }
}
