//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class EventImage
    {
        public int eventImageID { get; set; }
        public Nullable<int> eventID { get; set; }
        public Nullable<int> statusID { get; set; }
    
        public virtual EventInfo EventInfo { get; set; }
    }
}
