//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class Users
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Users()
        {
            this.EventInfo = new HashSet<EventInfo>();
        }
    
        public int userID { get; set; }
        public string userNameEn { get; set; }
        public string userNameAR { get; set; }
        public string userTel { get; set; }
        public string userEmail { get; set; }
        public Nullable<int> userTypeID { get; set; }
        public Nullable<int> statusID { get; set; }
        public string username { get; set; }
        public string password { get; set; }
    
        public virtual UserType UserType { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<EventInfo> EventInfo { get; set; }
    }
}
