//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MasterWebApp.Resource {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class CommonMessage {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal CommonMessage() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("MasterWebApp.Resource.CommonMessage", typeof(CommonMessage).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to بحث جديد.
        /// </summary>
        public static string AuthorBtnNew {
            get {
                return ResourceManager.GetString("AuthorBtnNew", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to رجوع.
        /// </summary>
        public static string back {
            get {
                return ResourceManager.GetString("back", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to تفعيل.
        /// </summary>
        public static string btnActive {
            get {
                return ResourceManager.GetString("btnActive", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to إغلاق.
        /// </summary>
        public static string btnClose {
            get {
                return ResourceManager.GetString("btnClose", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to حذف.
        /// </summary>
        public static string btnDelete {
            get {
                return ResourceManager.GetString("btnDelete", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to تمت.
        /// </summary>
        public static string btnDone {
            get {
                return ResourceManager.GetString("btnDone", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to تعديل.
        /// </summary>
        public static string btnEdit {
            get {
                return ResourceManager.GetString("btnEdit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to تجاهل.
        /// </summary>
        public static string btnIgnore {
            get {
                return ResourceManager.GetString("btnIgnore", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to جديد .
        /// </summary>
        public static string btnNew {
            get {
                return ResourceManager.GetString("btnNew", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ايقاف مؤقت.
        /// </summary>
        public static string btnPause {
            get {
                return ResourceManager.GetString("btnPause", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to استعادة.
        /// </summary>
        public static string btnRestore {
            get {
                return ResourceManager.GetString("btnRestore", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to حفظ.
        /// </summary>
        public static string btnSave {
            get {
                return ResourceManager.GetString("btnSave", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to بحث.
        /// </summary>
        public static string btnSubmit {
            get {
                return ResourceManager.GetString("btnSubmit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to عرض.
        /// </summary>
        public static string btnView {
            get {
                return ResourceManager.GetString("btnView", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to شركة انجز للخدمات العقارية.
        /// </summary>
        public static string companyName {
            get {
                return ResourceManager.GetString("companyName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to confirmDelete.
        /// </summary>
        public static string confirmDelete {
            get {
                return ResourceManager.GetString("confirmDelete", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to اتصل بنا.
        /// </summary>
        public static string contactUs {
            get {
                return ResourceManager.GetString("contactUs", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Count.
        /// </summary>
        public static string count {
            get {
                return ResourceManager.GetString("count", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to يجب أن تكون الملفات بصيغة .docx.
        /// </summary>
        public static string docFormatHint {
            get {
                return ResourceManager.GetString("docFormatHint", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to تحميل الملف.
        /// </summary>
        public static string downloadPdf {
            get {
                return ResourceManager.GetString("downloadPdf", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to -- اختر --.
        /// </summary>
        public static string drpSelect {
            get {
                return ResourceManager.GetString("drpSelect", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to يجب تسجيل الدخول للحصول على هذه الخدمة.
        /// </summary>
        public static string errorLogin {
            get {
                return ResourceManager.GetString("errorLogin", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to خطأ اثناء الحفظ.
        /// </summary>
        public static string erroWhenSave {
            get {
                return ResourceManager.GetString("erroWhenSave", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to يجب أن تكون الملفات بصيغة .jpg.
        /// </summary>
        public static string imgFormatHint {
            get {
                return ResourceManager.GetString("imgFormatHint", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to تم الدخول بنجاح .
        /// </summary>
        public static string islogin {
            get {
                return ResourceManager.GetString("islogin", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to استكمل البيانات وحاول مرة اخرى.
        /// </summary>
        public static string msgEmpty {
            get {
                return ResourceManager.GetString("msgEmpty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to لاتوجد بيانات.
        /// </summary>
        public static string noData {
            get {
                return ResourceManager.GetString("noData", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to يجب أن تكون الملفات بصيغة .pdf.
        /// </summary>
        public static string pdfFormatHint {
            get {
                return ResourceManager.GetString("pdfFormatHint", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to فعال.
        /// </summary>
        public static string rowActive {
            get {
                return ResourceManager.GetString("rowActive", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to مغلق.
        /// </summary>
        public static string rowClose {
            get {
                return ResourceManager.GetString("rowClose", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to الإصدار الحالي.
        /// </summary>
        public static string rowCurrent {
            get {
                return ResourceManager.GetString("rowCurrent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to مقفل.
        /// </summary>
        public static string rowLocked {
            get {
                return ResourceManager.GetString("rowLocked", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Not Current.
        /// </summary>
        public static string rowNoCurrent {
            get {
                return ResourceManager.GetString("rowNoCurrent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to متاح.
        /// </summary>
        public static string rowUnLocked {
            get {
                return ResourceManager.GetString("rowUnLocked", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to تم الحفظ بنجاح .
        /// </summary>
        public static string saveOk {
            get {
                return ResourceManager.GetString("saveOk", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to اختر.
        /// </summary>
        public static string selectItem {
            get {
                return ResourceManager.GetString("selectItem", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to محذوف.
        /// </summary>
        public static string status0 {
            get {
                return ResourceManager.GetString("status0", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to فعال.
        /// </summary>
        public static string status1 {
            get {
                return ResourceManager.GetString("status1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 988888.
        /// </summary>
        public static string te2 {
            get {
                return ResourceManager.GetString("te2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 268555555.
        /// </summary>
        public static string tel1 {
            get {
                return ResourceManager.GetString("tel1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to رفع ملف PDF.
        /// </summary>
        public static string uploadPDFFile {
            get {
                return ResourceManager.GetString("uploadPDFFile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to جميع الحقوق محفوظة للمكتبة الرقمية.
        /// </summary>
        public static string webFooter {
            get {
                return ResourceManager.GetString("webFooter", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to جميع الحقوق محفوظة للمكتبة الرقمية.
        /// </summary>
        public static string webFooterJournal {
            get {
                return ResourceManager.GetString("webFooterJournal", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to المكتبة الرقمية الأكاديمية.
        /// </summary>
        public static string webHeader {
            get {
                return ResourceManager.GetString("webHeader", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to المكتبة الرقمية الأكاديمية.
        /// </summary>
        public static string webHeaderJournal {
            get {
                return ResourceManager.GetString("webHeaderJournal", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to الموقع.
        /// </summary>
        public static string webSite {
            get {
                return ResourceManager.GetString("webSite", resourceCulture);
            }
        }
    }
}
