//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MasterWebApp.Resource {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class EventInfo {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal EventInfo() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("MasterWebApp.Resource.EventInfo", typeof(EventInfo).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to اسم الدولة.
        /// </summary>
        public static string countryID {
            get {
                return ResourceManager.GetString("countryID", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to من تاريخ.
        /// </summary>
        public static string dateFrom {
            get {
                return ResourceManager.GetString("dateFrom", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to الى تاريخ.
        /// </summary>
        public static string dateTo {
            get {
                return ResourceManager.GetString("dateTo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to تعديل الحدث.
        /// </summary>
        public static string editEvent {
            get {
                return ResourceManager.GetString("editEvent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to تاريخ الحدث.
        /// </summary>
        public static string eventDate {
            get {
                return ResourceManager.GetString("eventDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to وصف الحدث ( عربي ).
        /// </summary>
        public static string eventDescAr {
            get {
                return ResourceManager.GetString("eventDescAr", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to وصف الحدث ( انجليزي ).
        /// </summary>
        public static string eventDescEn {
            get {
                return ResourceManager.GetString("eventDescEn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to م.
        /// </summary>
        public static string eventID {
            get {
                return ResourceManager.GetString("eventID", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to اسم الحدث ( عربي ).
        /// </summary>
        public static string eventNameAr {
            get {
                return ResourceManager.GetString("eventNameAr", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to اسم الحدث ( انجليزي ).
        /// </summary>
        public static string eventNameEn {
            get {
                return ResourceManager.GetString("eventNameEn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to تصنيف الحدث.
        /// </summary>
        public static string eventTypeID {
            get {
                return ResourceManager.GetString("eventTypeID", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to خط العرض.
        /// </summary>
        public static string latitude {
            get {
                return ResourceManager.GetString("latitude", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to خط الطول.
        /// </summary>
        public static string longitude {
            get {
                return ResourceManager.GetString("longitude", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to بحث.
        /// </summary>
        public static string Search {
            get {
                return ResourceManager.GetString("Search", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to حالة السجل.
        /// </summary>
        public static string statusID {
            get {
                return ResourceManager.GetString("statusID", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to الأحداث.
        /// </summary>
        public static string title {
            get {
                return ResourceManager.GetString("title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to مدخل الحدث.
        /// </summary>
        public static string userID {
            get {
                return ResourceManager.GetString("userID", resourceCulture);
            }
        }
    }
}
